# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeremy Cline's Blog
email: jeremy@jcline.org
description: > # this means to ignore newlines until "baseurl:"
  This blog is about all things FOSS
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jcline.org" # the base hostname & protocol for your site
github_username:  jeremycline

# Build settings
markdown: kramdown
